service: screenshot-example
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs16.x

plugins:
  - serverless-offline

functions:
  screenshot:
    handler: handler.capture
    events:
      - httpApi:
          path: /
          method: get
    memorySize: 1536
    timeout: 1000
